# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_account.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QMessageBox
from PyQt5.QtCore import QDate,Qt
import qdarkstyle
import sys
import pymysql

import detail_mg_ac


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 950)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        Form.setFont(font)

        self.id_label = QtWidgets.QLabel(Form)
        self.id_label.setGeometry(QtCore.QRect(220, 40,100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")

        self.acc_label_2 = QtWidgets.QLabel(Form)
        self.acc_label_2.setGeometry(QtCore.QRect(220, 120, 100,50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.acc_label_2.setFont(font)
        self.acc_label_2.setObjectName("acc_label_2")

        self.bank_name_label_3 = QtWidgets.QLabel(Form)
        self.bank_name_label_3.setGeometry(QtCore.QRect(220, 200, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.bank_name_label_3.setFont(font)
        self.bank_name_label_3.setObjectName("bank_name_label_3")

        self.bank_address_label_4 = QtWidgets.QLabel(Form)
        self.bank_address_label_4.setGeometry(QtCore.QRect(170, 280, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.bank_address_label_4.setFont(font)
        self.bank_address_label_4.setObjectName("bank_address_label_4")

        self.balabce_label_5 = QtWidgets.QLabel(Form)
        self.balabce_label_5.setGeometry(QtCore.QRect(220, 360, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.balabce_label_5.setFont(font)
        self.balabce_label_5.setObjectName("balabce_label_5")

        self.maxpay_label_6 = QtWidgets.QLabel(Form)
        self.maxpay_label_6.setGeometry(QtCore.QRect(140, 440, 220, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.maxpay_label_6.setFont(font)
        self.maxpay_label_6.setObjectName("maxpay_label_6")

        self.ac_phone_label_7 = QtWidgets.QLabel(Form)
        self.ac_phone_label_7.setGeometry(QtCore.QRect(180, 520, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.ac_phone_label_7.setFont(font)
        self.ac_phone_label_7.setObjectName("ac_phone_label_7")

        self.register_date_label_8 = QtWidgets.QLabel(Form)
        self.register_date_label_8.setGeometry(QtCore.QRect(190, 600, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.register_date_label_8.setFont(font)
        self.register_date_label_8.setObjectName("register_date_label_8")

        self.co_number_label_9 = QtWidgets.QLabel(Form)
        self.co_number_label_9.setGeometry(QtCore.QRect(180, 680, 140, 50))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.co_number_label_9.setFont(font)
        self.co_number_label_9.setObjectName("co_number_label_9")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(460, 780, 90, 50))
        self.pushButton.setObjectName("pushButton")

        self.back_pushButton = QtWidgets.QPushButton(Form)
        self.back_pushButton.setGeometry(QtCore.QRect(430, 850, 150, 50))
        self.back_pushButton.setObjectName("back_pushButton")

        self.id_lineEdit = QtWidgets.QLineEdit(Form)
        self.id_lineEdit.setGeometry(QtCore.QRect(380, 40, 461, 50))
        self.id_lineEdit.setObjectName("id_lineEdit")

        self.ac_number_lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.ac_number_lineEdit_2.setGeometry(QtCore.QRect(380, 120, 461, 50))
        self.ac_number_lineEdit_2.setObjectName("ac_number_lineEdit_2")

        self.bank_name_lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.bank_name_lineEdit_3.setGeometry(QtCore.QRect(380, 200, 461, 50))
        self.bank_name_lineEdit_3.setObjectName("bank_name_lineEdit_3")

        self.bank_address_lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.bank_address_lineEdit_4.setGeometry(QtCore.QRect(380, 280, 461, 50))
        self.bank_address_lineEdit_4.setObjectName("bank_address_lineEdit_4")

        self.balace_lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.balace_lineEdit_5.setGeometry(QtCore.QRect(380, 360, 461, 50))
        self.balace_lineEdit_5.setObjectName("balace_lineEdit_5")

        self.maxpay_lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.maxpay_lineEdit_6.setGeometry(QtCore.QRect(380, 440, 461, 50))
        self.maxpay_lineEdit_6.setObjectName("maxpay_lineEdit_6")

        self.ac_phone_lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.ac_phone_lineEdit_7.setGeometry(QtCore.QRect(380, 520, 461, 50))
        self.ac_phone_lineEdit_7.setObjectName("ac_phone_lineEdit_7")

        self.register_date__lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.register_date__lineEdit_8.setGeometry(QtCore.QRect(380, 600, 461, 50))
        self.register_date__lineEdit_8.setObjectName("register_date__lineEdit_8")

        self.co_number_lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.co_number_lineEdit_9.setGeometry(QtCore.QRect(380, 680, 461, 50))
        self.co_number_lineEdit_9.setObjectName("co_number_lineEdit_9")

        self.pushButton.clicked.connect(self.add_acount_info)
        self.back_pushButton.clicked.connect(self.detail_mg_ac)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "账户添加"))
        self.id_label.setText(_translate("Form", "用户id"))
        self.acc_label_2.setText(_translate("Form", "账号"))
        self.bank_name_label_3.setText(_translate("Form", "开账户"))
        self.bank_address_label_4.setText(_translate("Form", "银行地址"))
        self.balabce_label_5.setText(_translate("Form", "余额"))
        self.maxpay_label_6.setText(_translate("Form", "每月最大支出"))
        self.ac_phone_label_7.setText(_translate("Form", "绑定电话"))
        self.register_date_label_8.setText(_translate("Form", "注册日期"))
        self.co_number_label_9.setText(_translate("Form", "公司账号"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.back_pushButton.setText(_translate("MainWindow", "返回账户列表"))
    def add_acount_info(self):
        id=self.id_lineEdit.text()
        ac_num=self.ac_number_lineEdit_2.text()
        bank_name=self.bank_name_lineEdit_3.text()
        bank_address=self.bank_address_lineEdit_4.text()
        balabce=self.balace_lineEdit_5.text()
        maxpay=self.maxpay_lineEdit_6.text()
        ac_phone=self.ac_phone_lineEdit_7.text()
        register_date=self.register_date__lineEdit_8.text()
        co_num=self.co_number_lineEdit_9.text()
        print(id,ac_num,bank_name,bank_address,balabce,maxpay,ac_phone,register_date,co_num)
        if (id == "" or ac_num == "" or bank_name == "" or bank_address == "" or balabce == "" or maxpay == "" or ac_phone == "" or register_date == "" or co_num == ""):
            print(QMessageBox.warning(self, "警告", "添加信息不可为空!", QMessageBox.Yes, QMessageBox.Yes))
            return
        try:
            self.db = pymysql.connect(host='localhost', port=3306, user="root", password='root', database='zhanghang',
                                      charset='utf8')
        except:
            QMessageBox.warning(self, '警告', "连接数据库故障", QMessageBox.Yes)
            self.db.rollback()
        sql = 'select * from t_accont where a_id="%s"' % id  # sql指令语句
        cur = self.db.cursor()  # 获取游标
        cur.execute(sql)  # 执行sql语句
        results = cur.fetchall()  # 通过fetchall获取数据
        print('results1:', results)
        if results:
            QMessageBox.warning(self, '警告', "该信息已存在", QMessageBox.Yes)
        else:
            books = ()
            sql = 'insert into t_account () value(%s,%s,%s,%s,%s,%s,%s,%s,%s)'
            cur.execute(sql, books)  # 执行sql语句
            self.db.commit()
            QMessageBox.warning(self, '标题', '已成功添加书籍，可继续添加', QMessageBox.Yes)
            self.id_lineEdit.clear()
            self.ac_number_lineEdit_2.clear()
            self.bank_name_lineEdit_3.clear()
            self.bank_address_lineEdit_4.clear()
            self.balace_lineEdit_5.clear()
            self.maxpay_lineEdit_6.clear()
            self.ac_phone_lineEdit_7.text()
            self.register_date__lineEdit_8.setDate(QDate.currentDate())
            self.db.close()
            cur.close()

    def detail_mg_ac(self):
        self.hide()  # 主界面的隐藏
        self.gtmc = detail_mg_ac.Ui_MainWindow()
        #注册界面打开
        self.gtmc.show()

if __name__ == '__main__':
    from PyQt5.Qt import *
    app = QtWidgets.QApplication(sys.argv) # 创建一个应用程序
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui1 = Ui_MainWindow()    # 创建设计好的窗口对象
    ui1.show()
    sys.exit(app.exec_())