# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QMainWindow
import qdarkstyle


class Ui_Form(object):
    def __init__(self):
        super(Ui_Form, self).__init__()
        self.ut = 0
        self.setupUi(self)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(493, 217)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        Form.setFont(font)
        self.user_label = QtWidgets.QLabel(Form)
        self.user_label.setGeometry(QtCore.QRect(190, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.zhanghao_label = QtWidgets.QLabel(Form)
        self.zhanghao_label.setGeometry(QtCore.QRect(120, 90, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.zhanghao_label.setFont(font)
        self.zhanghao_label.setObjectName("zhanghao_label")
        self.account_lineEdit = QtWidgets.QLineEdit(Form)
        self.account_lineEdit.setGeometry(QtCore.QRect(170, 90, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.account_lineEdit.setFont(font)
        self.account_lineEdit.setObjectName("account_lineEdit")
        self.passwod_label = QtWidgets.QLabel(Form)
        self.passwod_label.setGeometry(QtCore.QRect(120, 130, 54, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.passwod_label.setFont(font)
        self.passwod_label.setObjectName("passwod_label")
        self.password_lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.password_lineEdit_2.setGeometry(QtCore.QRect(170, 130, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.password_lineEdit_2.setFont(font)
        self.password_lineEdit_2.setObjectName("password_lineEdit_2")
        self.dengru_pushButton = QtWidgets.QPushButton(Form)
        self.dengru_pushButton.setGeometry(QtCore.QRect(200, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dengru_pushButton.setFont(font)
        self.dengru_pushButton.setObjectName("dengru_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.user_label.setText(_translate("Form", "用户登入"))
        self.zhanghao_label.setText(_translate("Form", "账号："))
        self.account_lineEdit.setInputMask(_translate("Form", "请输入账号"))
        self.passwod_label.setText(_translate("Form", "密码："))
        self.password_lineEdit_2.setInputMask(_translate("Form", "请输入密码"))
        self.dengru_pushButton.setText(_translate("Form", "登入"))


if __name__ == '__main__':
    from PyQt5.Qt import *
    app = QtWidgets.QApplication(sys.argv) # 创建一个应用程序
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

    ui1 = Ui_Form()    # 创建设计好的窗口对象
    ui1.show()
    sys.exit(app.exec_())